openapi: 3.1.0
info:
  title: Cine Rental Hub API
  version: 1.0.0
  description: API for managing movies, users, carts, and comments in the Cine Rental Hub.
paths:
  /movies:
    post:
      summary: Add a new movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
      responses:
        '201':
          description: Movie successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
    get:
      summary: Get a list of all movies
      responses:
        '200':
          description: A list of movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
  /movies/{movieId}:
    parameters:
      - name: movieId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Get a movie by ID
      responses:
        '200':
          description: A single movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
    put:
      summary: Update a movie by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
      responses:
        '200':
          description: Movie successfully updated
  /movies/deactivated/{movieId}:
    parameters:
      - name: movieId
        in: path
        required: true
        schema:
          type: integer
    patch:
      summary: Deactivate a movie by ID
      responses:
        '204':
          description: Movie successfully deleted
  /movies/activated/{movieId}:
    parameters:
      - name: movieId
        in: path
        required: true
        schema:
          type: integer
    patch:
      summary: Activate a movie by ID
      responses:
        '200':
          description: Movie successfully updated
  /movies/main_image/{movieId}:
    get:
      summary: Get the main image of a movie
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The main image of the movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
    put:
      summary: Set the main image of a movie
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image_id:
                  type: integer
      responses:
        '200':
          description: Main image successfully set
  /movies/image/{movieId}:
    parameters:
      - name: movieId
        in: path
        required: true
        schema:
          type: integer
    post:
      summary: Add an image to a movie
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '201':
          description: Image successfully added to the movie
    get:
      summary: Get all images of a movie
      responses:
        '200':
          description: A list of movie images
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
  /movies/image/{imageId}:
    delete:
      summary: Delete an image from an id
      parameters:
        - name: imageId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Image successfully deleted
components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
        available:
          type: boolean
        title:
          type: string
        release_date:
          type: string
          format: date
        daily_rental_price:
          type: number
          format: float
        purchase_price:
          type: number
          format: float
        description:
          type: string
        link:
          type: string
    Image:
      type: object
      properties:
        id:
          type: integer
        movie_id:
          type: integer
        image_url:
          type: string
        main_image:
          type: boolean
