version: '3.8'
services:
  vuejs-client:
    build:
       context: ./front
    ports:
      - "8080:8080"
    networks:
      - ubo-network

  mariadb:
    image: mariadb:11.3.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uboeventflow_bdd
    ports:
      - "3306:3306"
    volumes:
      - ./back/mariadb/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - mariadb-data:/var/lib/mysql
    networks:
      - ubo-network

  mongo:
    build:
      context:
        ./dockerMongodb
    ports:
      - "27017:27017"
    networks:
      - ubo-network

networks:
  ubo-network:
    external: true

volumes:
  mariadb-data:
  # mongodb-data:
