version: '3.8'
services:
#  vuejs-client:
#    build:
#       context: ./front
#    ports:
#      - "8080:8080"
#    networks:
#      - ubo-network

  mariadb:
    image: mariadb:11.3.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cine_rental_hub
    ports:
      - "3306:3306"
    volumes:
      - ./back/mariadb/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - mariadb-data:/var/lib/mysql
    networks:
      - ubo-network

#  mongo:
#    build:
#      context:
#        ./back/mongodb
#    ports:
#      - "27017:27017"
#    networks:
#      - ubo-network

  front:
    build:
      context:
        ./front
    ports:
      - "8080:8080"
    networks:
      - ubo-network

  node:
    build:
      context:
        ./back/node
    ports:
      - "3000:3000"
    networks:
      - ubo-network

  movie-api:
    build:
      context:
        ./back/api/movie
    ports:
      - "8082:8080"
    networks:
      - ubo-network

#  user-api:
#    build:
#      context:
#        ./back/api/user
#    ports:
#        - "8085:8080"
#    networks:
#          - ubo-network


networks:
  ubo-network:
    external: true

volumes:
  mariadb-data:
  # mongodb-data:
